### ISSUE TITLE
Add support for "Resource Owner Password Credentials Grant"

### ISSUE THREAD

**Issue by funkyferdy** [xperseguers/t3ext-oidc#15]
We would like, beside of the "CallbackURL"-Mode, also the possibility to log in with the ids-credentials directly on the FE/TYPO3-Login Form without sending the user to the external login page. 

See also:
[Resource Owner Password Credentials Grant](https://docs.wso2.com/display/IS520/Resource+Owner+Password+Credentials+Grant)
grant_type=password
We can control over ids if this type of auth is allowed or not on SP-basis.
Can look like this. For now only basic functionality. So, no password reset etc. Just simple login.
![grafik](https://cloud.githubusercontent.com/assets/22144187/25004938/14e9f1d2-2057-11e7-8369-d927c22bd52b.png)

After susscessfull login, same logic of mappings/Fields/roles etc. should be aplied. 

This will be the main way in the "SAC Usecase" for login in to the Portal. In our special case we will need further functions, but this are not in the scope of an "public". Will add other Issues for that.

**Comment by xperseguers** [comment]
If I get it right, the purpose is to show the username/password field but upon clicking on "Anmelden", you want those infos to be sent as ROPCG to WSO2 Identity Server.

If I get it right, then you probably don't want to show the "OpenID Connect" link because both authentication methods are logically mutually exclusive. This is not a must to be mutually exclusive but it does not make sense to show both authentication methods imho.

As such, I would suggest a configuration for the "mode" of the oidc authentication service: either "SSO" or just another authentication service. In non-SSO, it wouldn't hook into felogin to add support for additional fields, you would just need to use standard templates from felogin (or your own of course) and oidc would just catch the username/password and authenticate on its own to WSO2, just like a LDAP authentication service does.

Does it sound fine for you?

**Comment by funkyferdy** [comment]
> As such, I would suggest a configuration for the "mode" of the oidc authentication service: either "SSO" or just another authentication service. 

Yes, that sounds completely fine. The goal is to have both posibilities avaiable. One with the redirection over wso2 redirect/interface and one directly on sp/typo3 side. So the user does not need to "leave" the website (in a optimal case). For me is also fine if you can activate both ways at the same time like 

Sections/Partners will mostly use redirection (because we can not "fully trust" their Applications. But on the main sac Website we have everything "under control". For our usecase we will use own templates and functionalities. But that is another story :) For the public TER i think thats a good thing to have this 2 "Grant types" avaiable. There are some more, but not scope at the moment. See also [https://docs.wso2.com/display/IS520/OAuth+2.0+with+WSO2+Playground](https://docs.wso2.com/display/IS520/OAuth+2.0+with+WSO2+Playground)

**Comment by funkyferdy** [comment]
https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/Password.php

**Comment by funkyferdy** [comment]
@xperseguers: Regarding missing information in Session. It looks like there is a endpoint for that :)

For the " Resource Owner Password Credentials Grant. ROPWCG" you need to "exchange" something to get the actual token

Please read this one : [https://docs.wso2.com/m/mobile.action#page/60493966|https://docs.wso2.com/m/mobile.action#page/60493966]
