### ISSUE TITLE
Is it mandatory to have a fixed callback URI?

### ISSUE THREAD

**Issue by xperseguers** [xperseguers/t3ext-oidc#5]
@funkyferdy I wonder if the callback URI **must** be defined or if one may configure the server to accept an arbitrary callback instead?

**Comment by funkyferdy** [comment]
According to documentation yes for now:
https://docs.wso2.com/display/IS520/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

We have not 5.2 yet but will be upgrade in next month:
"From IS 5.2.0 onwards, regex based consumer URLs are supported when defining the callback URL."

But im still not sure if you can "Wildcard" like /index.php*

**Comment by funkyferdy** [comment]
From IS 5.2.0 onwards, regex based consumer URLs are supported when defining the callback URL. This enables you to configure multiple callback URLs for one application.
For example, if you have two service providers that use the same application, you can now define a regex pattern which will work for both callback URLs instead of having to configure two different applications for the two service providers. Assume the two callback URLs for your two service providers are as follows:

    https://myapp.com/callback
    https://testapp:8000/callback

To configure the callback URL to work for both of these URLs, set it using a regex pattern as follows:
regexp=(https://myapp.com/callback|https://testapp:8000/callback)
---------------------
So if we get IS 5.2.0 soon, a possible configuration on IS site could be https://mytypo3url.com/(anything allowed)
In this case it would be de default callback ur **IF** nothing is configured. would allow to use the complete power of user based or group based redirection configuration in felogin or any other place :)

![grafik](https://cloud.githubusercontent.com/assets/22144187/25991404/52237f2e-3703-11e7-99b9-0f0d54498876.png)

**Comment by funkyferdy** [comment]
@xperseguers : Not anymore. Maybe you can help me define a right regex pattern that does:
https://www.mydomain.tld/*anything?
